# Generated by Django 4.2.7 on 2026-06-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_fieldschedules_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldschedules',
            name='field',
            field=models.ForeignKey(blank=True, db_column='field_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fields.footballfields'),
        ),
        migrations.AddField(
            model_name='footballfields',
            name='field_type',
            field=models.ForeignKey(blank=True, db_column='field_type_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fields.fieldtypes'),
        ),
    ]
