# Generated by Django 4.2.7 on 2026-06-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinglogs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bookings',
            options={'managed': True},
        ),
    ]
