# Generated by Django 4.2.7 on 2026-06-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_fieldschedules_field_footballfields_field_type'),
        ('users', '0003_customers_user'),
        ('bookings', '0002_alter_bookinglogs_options_alter_bookings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglogs',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.bookings'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fields.footballfields'),
            preserve_default=False,
        ),
    ]
