# Generated by Django 4.2.7 on 2026-06-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('fields', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('booking', models.OneToOneField(blank=True, db_column='booking_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.bookings')),
                ('field', models.ForeignKey(db_column='field_id', on_delete=django.db.models.deletion.DO_NOTHING, to='fields.footballfields')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='users.customers')),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
    ]
