# Generated by Django 4.2.7 on 2026-06-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_fieldschedules_field_footballfields_field_type'),
        ('bookings', '0003_bookinglogs_booking_bookings_customer_bookings_field'),
        ('users', '0003_customers_user'),
        ('reviews', '0002_alter_reviews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='booking',
            field=models.OneToOneField(blank=True, db_column='booking_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.bookings'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='field',
            field=models.ForeignKey(db_column='field_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fields.footballfields'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.customers'),
            preserve_default=False,
        ),
    ]
