# Generated by Django 4.2.7 on 2026-06-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookinglogs_booking_bookings_customer_bookings_field'),
        ('users', '0003_customers_user'),
        ('payments', '0002_alter_payments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.bookings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.customers'),
            preserve_default=False,
        ),
    ]
