# Generated by Django 4.2.7 on 2026-06-17 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('field', models.ForeignKey(blank=True, db_column='field_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fields.footballfields')),
            ],
            options={
                'db_table': 'time_slots',
                'managed': True,
                'unique_together': {('field', 'slot_date', 'start_time')},
            },
        ),
    ]
